#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Check Prettier standards
npm run check-format ||
(
    echo 'prettier message : the code looks raw';
    false;
)

# Check ESLint Standards
npm run check-lint ||
(
        echo 'eslint message : the linting seems not ideal'
        false; 
)

# Check tsconfig standards
npm run check-types ||
(
    echo 'typescript message : 🤡😂❌🤡 Failed Type check. 🤡😂❌🤡'
    false;
)

# If everything passes... Now we can commit
echo '🤔🤔🤔🤔... Alright... Code looks good to me... Trying to build now. 🤔🤔🤔🤔'

npm run build ||
(
    echo '❌👷🔨❌ Build message: Build creation failed ❌👷🔨❌
    '
    false;
)

# If everything passes... Now we can commit
echo '✅ All checks passed . commiting code now ... ✅'

