#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

npm run lint:css:fix ||
(
    echo '❌ Stylelint messsage: linting failed ! ❌'
)

npm run build ||
(
    echo '❌👷🔨❌ Build message: Build creation failed ❌👷🔨❌
    '
    false;
)

# If everything passes... Now we can commit
echo '✅ All checks passed . commiting code now ... ✅'

